"""Initial migration

Revision ID: faec1295cc99
Revises: 
Create Date: 2024-11-22 13:10:54.978995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faec1295cc99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airlines',
    sa.Column('id_aerolinea', sa.Integer(), nullable=False),
    sa.Column('nombre_aerolinea', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_aerolinea')
    )
    op.create_table('airports',
    sa.Column('id_aeropuerto', sa.Integer(), nullable=False),
    sa.Column('nombre_aeropuerto', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_aeropuerto')
    )
    op.create_table('movements',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('flights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aerolinea', sa.Integer(), nullable=False),
    sa.Column('id_aeropuerto', sa.Integer(), nullable=False),
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('dia', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_aerolinea'], ['airlines.id_aerolinea'], ),
    sa.ForeignKeyConstraint(['id_aeropuerto'], ['airports.id_aeropuerto'], ),
    sa.ForeignKeyConstraint(['id_movimiento'], ['movements.id_movimiento'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flights')
    op.drop_table('movements')
    op.drop_table('airports')
    op.drop_table('airlines')
    # ### end Alembic commands ###
